In [1]:
import pandas as pd
from datetime import datetime  # Import datetime
df = r'C:\Users\SanthoshS\Desktop\DataEngineering\DataWarehouse\curated_schema\curated.csv'
df = pd.read_csv(df)
df.head()

,enrollment_id,employee_id,course_id,enrolled_date,completed_date,progress,ratings,category,course_name,course_duration,...,role_outcome,employee_name,current_role,skills,dateofbirth,dateofjoining,email,mobile_number,Address,yearofexperience
0,1,255,5,2024-08-29,2024-10-07,59,1.7,Neutral,Deep Learning Specialization,9,...,senior data scientist,Louis Jensen,junior data scientist,Python,2000-10-07,2013-12-27,taylor15@example.org,504983270830774,"42105 Peterson Forest Suite 215, Shawton, DC 3...",10
1,1,255,5,2024-08-29,2024-10-07,59,1.7,Neutral,Deep Learning Specialization,9,...,senior data scientist,Vicki Munoz,junior data engineer,Data Warehousing,1960-11-29,2020-02-14,ythompson@example.org,7005862536961,"85235 Schmidt Loop Apt. 132, West Sheila, VT 0...",4
2,2,391,4,2024-05-11,2024-09-26,0,4.8,Positive,Advanced Machine Learning,4,...,senior data scientist,Jeffrey Hill,junior software engineer,CSS,1998-01-09,2022-09-07,castillobenjamin@example.com,34957806305995,"7921 May Forest Suite 338, Davidmouth, VI 78710",2
3,3,384,3,2023-01-11,2023-03-13,83,3.0,Neutral,Data Analysis with Pandas,4,...,junior data scientist,Albert Tucker,senior data analyst,Statistics,2001-10-04,2007-12-24,qmay@example.net,369822945908927,"1278 Daniel Dale Suite 110, New Savannahhaven,...",16
4,3,384,3,2023-01-11,2023-03-13,83,3.0,Neutral,Data Analysis with Pandas,4,...,junior data scientist,Holly Carter,junior data scientist,Python,1965-04-22,2021-06-19,twong@example.org,7509539224,"466 Michelle Row, Alexandershire, LA 79304",3

In [2]:
# Drop specified columns from the DataFrame, ignoring any that are not found
df.drop([
    'enrollment_id', 'employee_id', 'course_id', 'enrolled_date', 
    'completed_date', 'progress', 'ratings', 'employee_name', 
    'price', 'course_duration', 'email', 'mobile_number', 
    'Address', 'dateofbirth', 'dateofjoining'
], 
        axis=1, inplace=True, errors='ignore')


# Display the first few rows of the updated DataFrame
df.head()

,category,course_name,outcome_skill,role_outcome,current_role,skills,yearofexperience
0,Neutral,Deep Learning Specialization,Natural Language Processing,senior data scientist,junior data scientist,Python,10
1,Neutral,Deep Learning Specialization,Natural Language Processing,senior data scientist,junior data engineer,Data Warehousing,4
2,Positive,Advanced Machine Learning,TensorFlow,senior data scientist,junior software engineer,CSS,2
3,Neutral,Data Analysis with Pandas,Python,junior data scientist,senior data analyst,Statistics,16
4,Neutral,Data Analysis with Pandas,Python,junior data scientist,junior data scientist,Python,3

In [3]:
df.dtypes

category            object
course_name         object
outcome_skill       object
role_outcome        object
current_role        object
skills              object
yearofexperience     int64
dtype: object

## Feature Engineering

In [4]:
df['feedback_category'] = df['category']
bins = [0, 2, 5, 10, 20, float('inf')]  # Binning intervals
labels = ['0-2', '2-5', '5-10', '10-20', '20+']  # Labels for each bin

# Binning the 'yearofexperience' column into categories
df['yearofexperience_category'] = pd.cut(df['yearofexperience'], bins=bins, labels=labels, right=False)

# Convert the new column to categorical type
df['yearofexperience_category'] = df['yearofexperience_category'].astype('category')
df.head()

,category,course_name,outcome_skill,role_outcome,current_role,skills,yearofexperience,feedback_category,yearofexperience_category
0,Neutral,Deep Learning Specialization,Natural Language Processing,senior data scientist,junior data scientist,Python,10,Neutral,10-20
1,Neutral,Deep Learning Specialization,Natural Language Processing,senior data scientist,junior data engineer,Data Warehousing,4,Neutral,2-5
2,Positive,Advanced Machine Learning,TensorFlow,senior data scientist,junior software engineer,CSS,2,Positive,2-5
3,Neutral,Data Analysis with Pandas,Python,junior data scientist,senior data analyst,Statistics,16,Neutral,10-20
4,Neutral,Data Analysis with Pandas,Python,junior data scientist,junior data scientist,Python,3,Neutral,2-5

In [5]:
# Converting specific columns to categorical type
df['course_name'] = df['course_name'].astype('category')
df['outcome_skill'] = df['outcome_skill'].astype('category')
df['role_outcome'] = df['role_outcome'].astype('category')
df['current_role'] = df['current_role'].astype('category')
df['skills'] = df['skills'].astype('category')
df['feedback_category'] = df['feedback_category'].astype('category')

# Checking the updated data types
print(df.dtypes)

category                       object
course_name                  category
outcome_skill                category
role_outcome                 category
current_role                 category
skills                       category
yearofexperience                int64
feedback_category            category
yearofexperience_category    category
dtype: object

In [6]:
df.drop(['yearofexperience','category'],axis=1,inplace=True)
df.head()

,course_name,outcome_skill,role_outcome,current_role,skills,feedback_category,yearofexperience_category
0,Deep Learning Specialization,Natural Language Processing,senior data scientist,junior data scientist,Python,Neutral,10-20
1,Deep Learning Specialization,Natural Language Processing,senior data scientist,junior data engineer,Data Warehousing,Neutral,2-5
2,Advanced Machine Learning,TensorFlow,senior data scientist,junior software engineer,CSS,Positive,2-5
3,Data Analysis with Pandas,Python,junior data scientist,senior data analyst,Statistics,Neutral,10-20
4,Data Analysis with Pandas,Python,junior data scientist,junior data scientist,Python,Neutral,2-5

In [7]:
unique_count = df['current_role'].nunique()
print(unique_count)

8

In [8]:
df.columns

Index(['course_name', 'outcome_skill', 'role_outcome', 'current_role',
       'skills', 'feedback_category', 'yearofexperience_category'],
      dtype='object')

In [9]:
df.dtypes

course_name                  category
outcome_skill                category
role_outcome                 category
current_role                 category
skills                       category
feedback_category            category
yearofexperience_category    category
dtype: object

In [10]:
df['feedback_category'].head()

0     Neutral
1     Neutral
2    Positive
3     Neutral
4     Neutral
Name: feedback_category, dtype: category
Categories (3, object): ['Negative', 'Neutral', 'Positive']

In [11]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans
import numpy as np


# Correctly define categorical_columns
categorical_columns = ['course_name', 'outcome_skill', 'role_outcome', 
                       'current_role', 'skills', 'feedback_category', 
                       'yearofexperience_category']

# Preprocess: Convert columns to string and strip whitespace
for column in categorical_columns:
    df[column] = df[column].astype(str).str.strip()  # Convert to string and strip whitespace

# Use OneHotEncoder with handle_unknown='ignore'
encoder = OneHotEncoder(drop='first', handle_unknown='ignore')
encoded_features = encoder.fit_transform(df[categorical_columns]).toarray()

# Fit K-Means Clustering
n_clusters = 9  # Choose the number of clusters based on your data
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(encoded_features)

# Add cluster labels to the original DataFrame
df['cluster'] = kmeans.labels_

# Function to recommend a course based on a new employee's data
def recommend_courses_based_on_role(new_employee_data, encoder, kmeans, df):
    # Clean and prepare the new employee data
    if len(new_employee_data) != len(categorical_columns):
        raise ValueError("New employee data must match the number of categorical columns.")

    # Convert the new employee data to a DataFrame
    new_employee_df = pd.DataFrame([new_employee_data], columns=categorical_columns)

    # Ensure all values are in the expected format (string and stripped)
    for column in categorical_columns:
        new_employee_df[column] = new_employee_df[column].astype(str).str.strip()

    # Get the desired role outcome and current skills
    desired_role_outcome = new_employee_df['role_outcome'].values[0]
    current_role = new_employee_df['current_role'].values[0]
    current_skills = set(new_employee_df['skills'].values[0].split(','))

    # Filter courses based on the desired role outcome and relevant skills
    relevant_courses = df[df['role_outcome'] == desired_role_outcome]

    # Further filter by checking if the skills are related to the courses
    recommended_courses = []
    for _, course in relevant_courses.iterrows():
        course_skills = set(course['outcome_skill'].split(','))
        if not current_skills.intersection(course_skills):  # Recommend if there is no skill match
            recommended_courses.append(course['course_name'])

    return list(set(recommended_courses))  # Return unique course names

# New employee data (example)
new_employee_data = ['Building Data Pipelines', 'Data Modeling', 
                     'junior data engineer', 'junior software engineer', 
                     'Microservices, Sql', 'Neutral', '5-10']

# Get recommended courses
recommended_courses = recommend_courses_based_on_role(new_employee_data, encoder, kmeans, df)
print(f'Recommended Courses: {recommended_courses}')

Recommended Courses: ['Introduction to Data Engineering', 'ETL Fundamentals', 'Building Data Pipelines']

In [12]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Function for hybrid course recommendation
def hybrid_recommendation(new_employee_data, df):
    desired_role_outcome = new_employee_data[2]  # role_outcome
    current_skills = set(new_employee_data[4].split(','))  # skills

    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome]

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Get the current employee's skills as a TF-IDF vector
    employee_skills_str = ' '.join(current_skills)
    employee_vector = vectorizer.transform([employee_skills_str])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame
    relevant_courses['similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].tolist()

    return recommended_courses

# New employee data (example)
new_employee_data = ['Building Data Pipelines', 'Data Modeling', 
                     'junior data engineer', 'junior software engineer', 
                     'Microservices, SQL', 'Neutral', '5-10']

# Get recommended courses
recommended_courses = set(hybrid_recommendation(new_employee_data, df))
print(f'Recommended Courses: {recommended_courses}')

Recommended Courses: {'Introduction to Data Engineering', 'ETL Fundamentals', 'Building Data Pipelines'}

C:\Users\SanthoshS\AppData\Local\Temp\ipykernel_11572\3163423998.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  relevant_courses['similarity'] = cosine_similarities.flatten()

In [13]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Function for hybrid course recommendation
def hybrid_recommendation(new_employee_data, df):
    desired_role_outcome = new_employee_data[2]  # role_outcome
    current_skills = set(new_employee_data[4].split(','))  # skills

    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome].copy()  # Use .copy()

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Get the current employee's skills as a TF-IDF vector
    employee_skills_str = ' '.join(current_skills)
    employee_vector = vectorizer.transform([employee_skills_str])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame using .loc
    relevant_courses.loc[:, 'similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].tolist()

    return recommended_courses

# New employee data (example)
new_employee_data = ['Building Data Pipelines', 'Data Modeling', 
                     'junior data engineer', 'junior software engineer', 
                     'SQL, Python', 'Neutral', '5-10']

# Get recommended courses
recommended_courses = set(hybrid_recommendation(new_employee_data, df))
print(f'Recommended Courses: {recommended_courses}')

Recommended Courses: {'Introduction to Data Engineering', 'ETL Fundamentals', 'Building Data Pipelines'}

In [14]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Function for hybrid course recommendation
def hybrid_recommendation(new_employee_data, df):
    desired_role_outcome = new_employee_data[2]  # role_outcome
    current_skills = set(new_employee_data[4].split(','))  # skills

    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome].copy()  # Use .copy()

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Get the current employee's skills as a TF-IDF vector
    employee_skills_str = ' '.join(current_skills)
    employee_vector = vectorizer.transform([employee_skills_str])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame using .loc
    relevant_courses.loc[:, 'similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].tolist()

    # Suggest skills needed for the desired role outcome
    suggested_skills = set()
    for _, course in relevant_courses.iterrows():
        course_skills = set(course['outcome_skill'].split(','))
        suggested_skills.update(course_skills)

    # Return both recommended courses and suggested skills
    return recommended_courses, list(suggested_skills)

# New employee data (example)
new_employee_data = ['Building Data Pipelines', 'Data Modeling', 
                     'senior software engineer', 'junior software engineer', 
                     'Microservices, SQL', 'Neutral', '5-10']

# Get recommended courses and skills
recommended_courses, suggested_skills = hybrid_recommendation(new_employee_data, df)
print(f"Recommended Courses: {set(recommended_courses)}")  # Proper set formatting
print(f"Suggested Skills: {suggested_skills}")

Recommended Courses: {'DevOps Essentials', 'Microservices Architecture', 'Advanced JavaScript'}
Suggested Skills: ['Cloud Computing', 'DevOps']

In [17]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize a list to store user input and output data
user_data_storage = []

# Function for hybrid course recommendation
def hybrid_recommendation(new_employee_data, df):
    desired_role_outcome = new_employee_data[2]  # role_outcome
    current_skills = set(new_employee_data[4].split(','))  # skills

    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome].copy()  # Use .copy()

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Get the current employee's skills as a TF-IDF vector
    employee_skills_str = ' '.join(current_skills)
    employee_vector = vectorizer.transform([employee_skills_str])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame using .loc
    relevant_courses.loc[:, 'similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].unique().tolist()

    # Suggest skills needed for the desired role outcome
    suggested_skills = set()
    for _, course in relevant_courses.iterrows():
        course_skills = set(course['outcome_skill'].split(','))
        suggested_skills.update(course_skills)

    # Ensure suggested skills are unique
    suggested_skills = list(suggested_skills)

    # Store the user input and output in the data storage
    user_data_storage.append({
        'input_role_outcome': desired_role_outcome,
        'input_current_skills': list(current_skills),
        'recommended_courses': recommended_courses,
        'suggested_skills': suggested_skills
    })

    # Return both recommended courses and suggested skills
    return recommended_courses, suggested_skills

# New employee data (example)
new_employee_data = ['Building Data Pipelines', 'Data Modeling', 
                     'senior software engineer', 'junior software engineer', 
                     'Microservices, SQL', 'Neutral', '5-10']

# Assuming df is already defined and populated with course data
recommended_courses, suggested_skills = hybrid_recommendation(new_employee_data, df)

# Print the results
print(f"Recommended Courses: {set(recommended_courses)}")  # Proper set formatting
print(f"Suggested Skills: {suggested_skills}")

# Convert user data storage to a DataFrame
user_data_df = pd.DataFrame(user_data_storage)

# Save to CSV file
user_data_df.to_csv('user_data_storage.csv', index=False)

# To view the saved CSV data
print("\nData saved to user_data_storage.csv")

Recommended Courses: {'DevOps Essentials', 'Microservices Architecture', 'Advanced JavaScript'}
Suggested Skills: ['Cloud Computing', 'DevOps']

Data saved to user_data_storage.csv

In [21]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize a list to store user input and output data
user_data_storage = []

# Function for hybrid course recommendation
def hybrid_recommendation(employee_id, desired_role_outcome, current_skills, df):
    current_skills_set = set(current_skills.split(','))  # Convert to set for uniqueness

    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome].copy()

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Get the current employee's skills as a TF-IDF vector
    employee_vector = vectorizer.transform([' '.join(current_skills_set)])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame
    relevant_courses['similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].unique().tolist()

    # Suggest skills needed for the desired role outcome
    suggested_skills = set()
    for _, course in relevant_courses.iterrows():
        course_skills = set(course['outcome_skill'].split(','))
        suggested_skills.update(course_skills)

    # Ensure suggested skills are unique
    suggested_skills = list(suggested_skills)

    # Store the user input and output in the data storage
    user_data_storage.append({
        'employee_id': employee_id,
        'input_role_outcome': desired_role_outcome,
        'input_current_skills': current_skills_set,
        'recommended_courses': recommended_courses,
        'suggested_skills': suggested_skills
    })

    return recommended_courses, suggested_skills

# Collect user input
employee_id = input("Please enter your Employee ID: ")
desired_role_outcome = input("Please enter your desired role outcome: ")
current_skills = input("Please enter your current skills (comma-separated): ")

# Assuming df is already defined and populated with course data
recommended_courses, suggested_skills = hybrid_recommendation(employee_id, desired_role_outcome, current_skills, df)

# Print the results
print(f"Recommended Courses: {set(recommended_courses)}")  # Proper set formatting
print(f"Suggested Skills: {suggested_skills}")

# Convert user data storage to a DataFrame
user_data_df = pd.DataFrame(user_data_storage)

# Save to CSV file
user_data_df.to_csv('user_data_storage.csv', index=False)

# To confirm the data was saved
print("\nData saved to user_data_storage.csv")

Recommended Courses: {'Big Data Technologies', 'Data Architecture and Design', 'Cloud Data Engineering'}
Suggested Skills: ['Data Lakes', 'Hadoop', 'Spark']

Data saved to user_data_storage.csv

In [28]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize a list to store user input and output data
user_data_storage = []

# Function for hybrid course recommendation
def hybrid_recommendation(employee_id, desired_role_outcome, current_skills, completed_course, years_of_experience, current_role, df):
    current_skills_set = set(current_skills.split(','))
    
    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome].copy()

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Prepare a string combining current skills and completed courses
    combined_skills = ' '.join(current_skills_set) + ' ' + completed_course
    employee_vector = vectorizer.transform([combined_skills])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame
    relevant_courses['similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].unique().tolist()

    # Suggest skills needed for the desired role outcome, considering current role and experience
    suggested_skills = set()
    for _, course in relevant_courses.iterrows():
        course_skills = set(course['outcome_skill'].split(','))
        suggested_skills.update(course_skills)

    # Ensure suggested skills are unique
    suggested_skills = list(suggested_skills)

    # Store the user input and output in the data storage
    user_data_storage.append({
        'employee_id': employee_id,
        'input_role_outcome': desired_role_outcome,
        'input_current_skills': list(current_skills_set),
        'completed_course': completed_course,
        'years_of_experience': years_of_experience,
        'current_role': current_role,
        'recommended_courses': recommended_courses,
        'suggested_skills': suggested_skills
    })

    return recommended_courses, suggested_skills

# Collect user input
employee_id = input("Please enter your Employee ID: ")
desired_role_outcome = input("Please enter your desired role outcome: ")
current_skills = input("Please enter your current skills (comma-separated): ")
completed_course = input("Please enter the name of any completed course: ")
years_of_experience = input("Please enter your years of experience: ")
current_role = input("Please enter your current role: ")

# Assuming df is already defined and populated with course data
recommended_courses, suggested_skills = hybrid_recommendation(
    employee_id,
    desired_role_outcome,
    current_skills,
    completed_course,
    years_of_experience,
    current_role,
    df
)

# Print the results
print(f"Recommended Courses: {set(recommended_courses)}")  # Proper set formatting
print(f"Suggested Skills: {suggested_skills}")

# Convert user data storage to a DataFrame
user_data_df = pd.DataFrame(user_data_storage)

# Append to CSV file
user_data_df.to_csv('user_data_storage.csv', mode='a', header=not pd.io.common.file_exists('user_data_storage.csv'), index=False)

# To confirm the data was saved
print("\nData saved to user_data_storage.csv")

Recommended Courses: {'Big Data Technologies', 'Cloud Data Engineering', 'Data Architecture and Design'}
Suggested Skills: ['Data Lakes', 'Hadoop', 'Spark']

Data saved to user_data_storage.csv

In [33]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize a list to store user input and output data
user_data_storage = []

# Function for hybrid course recommendation
def hybrid_recommendation(employee_id, desired_role_outcome, current_skills, completed_courses, years_of_experience, current_role, df):
    current_skills_set = set(current_skills.split(','))
    completed_courses_set = {course.strip() for course in completed_courses.split(',')}  # Handle multiple completed courses

    # Filter courses based on the desired role outcome
    relevant_courses = df[df['role_outcome'] == desired_role_outcome].copy()

    # Create a TF-IDF vectorizer for the outcome skills
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(relevant_courses['outcome_skill'])

    # Prepare a string combining current skills and completed courses
    combined_skills = ' '.join(current_skills_set) + ' ' + ' '.join(completed_courses_set)
    employee_vector = vectorizer.transform([combined_skills])

    # Compute cosine similarity between the employee skills and course skills
    cosine_similarities = cosine_similarity(employee_vector, tfidf_matrix)

    # Add similarity scores to the relevant courses DataFrame
    relevant_courses['similarity'] = cosine_similarities.flatten()

    # Sort courses by similarity score and return the top recommendations
    recommended_courses = relevant_courses.sort_values(by='similarity', ascending=False)['course_name'].unique().tolist()

    # Filter out courses that the user has already completed
    recommended_courses = [course for course in recommended_courses if course not in completed_courses_set]

    # Suggest skills needed for the desired role outcome
    suggested_skills = set()
    for _, course in relevant_courses.iterrows():
        course_skills = set(course['outcome_skill'].split(','))
        suggested_skills.update(course_skills)

    # Remove skills that the user already has
    suggested_skills = [skill for skill in suggested_skills if skill not in current_skills_set]

    # Ensure suggested skills are unique
    suggested_skills = list(set(suggested_skills))

    # Store the user input and output in the data storage
    user_data_storage.append({
        'employee_id': employee_id,
        'input_role_outcome': desired_role_outcome,
        'input_current_skills': list(current_skills_set),
        'completed_courses': list(completed_courses_set),
        'years_of_experience': years_of_experience,
        'current_role': current_role,
        'recommended_courses': recommended_courses,
        'suggested_skills': suggested_skills
    })

    return recommended_courses, suggested_skills

# Collect user input
employee_id = input("Please enter your Employee ID: ")
desired_role_outcome = input("Please enter your desired role outcome: ")
current_skills = input("Please enter your current skills (comma-separated): ")
completed_courses = input("Please enter the names of any completed courses (comma-separated): ")
years_of_experience = input("Please enter your years of experience: ")
current_role = input("Please enter your current role: ")

# Assuming df is already defined and populated with course data
recommended_courses, suggested_skills = hybrid_recommendation(
    employee_id,
    desired_role_outcome,
    current_skills,
    completed_courses,
    years_of_experience,
    current_role,
    df
)

# Print the results
print(f"Recommended Courses: {set(recommended_courses)}")  # Proper set formatting
print(f"Suggested Skills: {suggested_skills}")

# Convert user data storage to a DataFrame
user_data_df = pd.DataFrame(user_data_storage)

# Append to CSV file
user_data_df.to_csv('user_data_storage.csv', mode='a', header=not pd.io.common.file_exists('user_data_storage.csv'), index=False)

# To confirm the data was saved
print("\nData saved to user_data_storage.csv")

Recommended Courses: {'Advanced Machine Learning', 'AI for Everyone', 'Deep Learning Specialization'}
Suggested Skills: ['Natural Language Processing', 'TensorFlow']

Data saved to user_data_storage.csv